### PR TITLE
Adding Use context

### PR DESCRIPTION
**Pull request by jiya10208**
Description
Optimize the code using context to make it readable.

Context
Current Behavior:
as everything is in one page app, it makes the code look a little too messy.

Expected Behavior:
For better developer experience using use Context can make the code look really understandable.

Environment

Browser (if applicable):

### CODE REVIEW

**Comment by jiya10208** [comment]
I am not very good at using github so please tell me if i am making mistake or anything. I am simply going with flow rn.

**Review by Nitya-Pasrija — APPROVED** [review]
The routing work is good :)

**Comment by Nitya-Pasrija** [comment]
> I am not very good at using github so please tell me if i am making mistake or anything. I am simply going with flow rn.

Hey @jiya10208 
Just try not to make this many commit changes that would be preferred, rest you are doing great :)

**Comment by i-am-SnehaChauhan** [comment]
Hey @jiya10208, App.js and Navbar.js files have a merge conflict. Could you please sync your forked repository, make the necessary changes, and then submit your pull request. I can merge it once that's done.

**Comment by Nitya-Pasrija** [comment]
There are issues with the app.css file as well

**Pull request closed without merging**
