### PR TITLE
Improved hover state of search bar and fixed some warnings

### PR DESCRIPTION
**Pull request by A-4-Atom**
Improved hover state of search bar
changed color of search button on hover for better visibility
Fixed some warnings like using class instead of className, not using key prop for lists, no alt attribute for image etc.

If you find any mistakes just let me know I will fix and commit the changes again.
see issue #4

### CODE REVIEW

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Hey @A-4-Atom 
There are some conflicts in this PR in the App.js file which may cause trouble. Kindly look into it.

**Comment by A-4-Atom** [comment]
@Nitya-Pasrija
I've resolved the merge conflict

**Comment by i-am-SnehaChauhan** [comment]
Hey @A-4-Atom, App.js and Recipe.js files have a merge conflict. Could you please sync your forked repository, make the necessary changes, and then submit your pull request. I can merge it once that's done.

**Comment by A-4-Atom** [comment]
@i-am-SnehaChauhan I fixed it, there are no merge conflicts anymore.

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
image

The conflicts are still there, let's work this out. Try doing a git pull so that your code is in sync and we will merge the PR, once it's resolved

**Pull request closed without merging**
