### PR TITLE
Makin Login Functional #5 

### PR DESCRIPTION
**Pull request by acecoder7**
Here is the demo of login functionality with auth0 as required

https://drive.google.com/file/d/1df1thUMIS58Q1zu7p5v-19oxzBJBfxwK/view?usp=drive_link
(since file size exceeds hence uploaded on drive)

Highlighting the features added in this PR under issue- #5 
- A working login and signup using [Auth0](https://auth0.com/)
- login and signup via google and email/password is enabled
- A customized login/signup interface
- necessary changes in navbar ( adding login/logout/profile dropdown)
- a simple and clean profile page showing profile image, user name, user email.
- logout functional
- a basic frontend routing along with organizing the code in different folders and files as per the requirements of this issue

Additionally adding ss of few pages for easy reference
Screenshot (528)
Screenshot (529)
Screenshot (530)

### CODE REVIEW

**Comment by i-am-SnehaChauhan** [comment]
Hey @acecoder7, Great Work.

**Review by i-am-SnehaChauhan — APPROVED** [review]

**Comment by i-am-SnehaChauhan** [comment]
@acecoder7 it is not working 
image

**Comment by i-am-SnehaChauhan** [comment]
Please Resolve this.

**Comment by acecoder7** [comment]
> @acecoder7 it is not working 

Since this is not hosted somewhere and running locally on localhost, and you are probably using another port number (other than 3000).

I have only added localhost:3000 in redirects and callbacks URI, because of which it is not working for any other port numbers

Screenshot (531)

Let me know if any other localhost I should add in Application URIs. 

@i-am-SnehaChauhan

**Comment by Nitya-Pasrija** [comment]
This is amazing work <333
 @acecoder7

**Review by Nitya-Pasrija — APPROVED** [review]

**Pull request merged**
